# Generated by Django 2.2.6 on 2019-10-19 09:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [migrations.swappable_dependency(settings.AUTH_USER_MODEL)]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name="Institution",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("description", models.TextField(default=None)),
                (
                    "types",
                    models.IntegerField(
                        choices=[
                            (1, "fundacja"),
                            (2, "organizacja pozarządowa"),
                            (3, "zbiórka lokalna"),
                        ],
                        default=1,
                    ),
                ),
                ("category", models.ManyToManyField(to="donation.Category")),
            ],
        ),
        migrations.CreateModel(
            name="Donation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField()),
                ("address", models.CharField(max_length=128)),
                ("phone_number", models.CharField(max_length=32)),
                ("city", models.CharField(max_length=64)),
                ("zip_code", models.CharField(max_length=32)),
                ("pick_up_date", models.DateField()),
                ("pick_up_time", models.DateTimeField()),
                ("pick_up_comment", models.TextField(null=True)),
                ("category", models.ManyToManyField(to="donation.Category")),
                (
                    "institution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="donation.Institution",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
