# Generated by Django 2.2.6 on 2019-10-17 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("donation", "0001_initial")]

    operations = [
        migrations.AlterField(
            model_name="donation",
            name="categories",
            field=models.ManyToManyField(null=True, to="donation.Categorie"),
        ),
        migrations.AlterField(
            model_name="institution",
            name="categories",
            field=models.ManyToManyField(null=True, to="donation.Categorie"),
        ),
    ]
